[transcribe]
# ไฟล์อินพุตเริ่มต้น (เปลี่ยนชื่อไฟล์ตามที่ต้องการ)
input = 1.mp3

# ไฟล์ข้อความเอาต์พุตเริ่มต้น
output = output.txt

# ขนาดโมเดล Whisper: tiny, base, small, medium, large
model = small

# ภาษาในไฟล์เสียง:
#   auto = ให้โมเดลตรวจเอง
#   th   = ภาษาไทย
#   en   = อังกฤษ
#   ja   = ญี่ปุ่น
language = auto

# โหมดงาน:
#   transcribe = ถอดเสียงเป็นข้อความตามภาษาเดิม
#   translate  = แปลเป็นภาษาอังกฤษ
task = transcribe

# ความยาวแต่ละ chunk (วินาที)
chunk_sec = 15

[proxy]
# ใช้ Proxy หรือไม่ (true/false)
use_proxy = true

# ถ้าต้องการใช้ Proxy ให้กรอกด้านล่างนี้
host = proxy-si.mahidol
port = 8080
user = sarawut.shi@mahidol.ac.th
pass = 040929571a115p
